'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Research_management.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1394392_background_images_for_login_page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1394392-background-images-for-login-page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1RMP_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1RMP_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _460511_isro_maiden_moon_craft_bangalore_countdown_group_of_people_human_interest_india_moon_people_photography_pallava_bagla_getty_images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("460511-isro-maiden-moon-craft-bangalore-countdown-group-of-people-human-interest-"& _ 
                        "india-moon-people-photography-pallava-bagla-getty-images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _700781main_ladee_2_full_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("700781main_ladee_2_full_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _75345ce3b53e24e12fa3cb8778603b6e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("75345ce3b53e24e12fa3cb8778603b6e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CEAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CEAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property europeanspallationsource01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("europeanspallationsource01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gdm3_6_login_screen_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gdm3.6-login-screen-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gdm31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gdm31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gen_Research_banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gen Research banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gen_Research_banner1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gen Research banner1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grants_management_life_cycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grants-management-life-cycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grants_management_life_cycle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grants-management-life-cycle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_research_lab_9_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home-research-lab-9-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_researchHD_global1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_researchHD_global1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_researchHD_global11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_researchHD_global11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_researchHD_global12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_researchHD_global12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_researchHD_global13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_researchHD_global13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImperialComputing_103_1___tojpeg_1414403785394_x1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImperialComputing-103(1)--tojpeg_1414403785394_x1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IN14_GSLV_104065f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IN14_GSLV_104065f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_research() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_research", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_research1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_research1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property isro_rocket_launch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("isro_rocket_launch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lg_aramco_hrc_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lg_aramco_hrc_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lg_aramco_hrc_61() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lg_aramco_hrc_61", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mars_mission_PTI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mars_mission_PTI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mk3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mk3_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nasa_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nasa-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nasa_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nasa-21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nasa_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nasa-22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nasa_isro_flight_sky_earth_space_rocket_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nasa-isro-flight-sky-earth-space-rocket-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nasa_isro_flight_sky_earth_space_rocket_min1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nasa-isro-flight-sky-earth-space-rocket-min1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nasa_isro_flight_sky_earth_space_rocket_min2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nasa-isro-flight-sky-earth-space-rocket-min2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NW_View_Phase1_960x400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NW-View-Phase1_960x400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Research__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Research (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__1___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (1) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__1___1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (1) (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__1___1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (1) (1)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__1___1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (1) (1)3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__1___1_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (1) (1)4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__1___1_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (1) (1)5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__1___1_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (1) (1)6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (2)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (2)3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__2_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (2)4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (3)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research__3_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research (3)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Research_Liquid_Glass1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Research-Liquid-Glass1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Research_Liquid_Glass11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Research-Liquid-Glass11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Research_Liquid_Glass12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Research-Liquid-Glass12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research_pic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research-pic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property research5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property researchlabs1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("researchlabs1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property researchlabs11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("researchlabs11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rfroxm_8eu22csx_nxlqew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rfroxm_8eu22csx_nxlqew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rfroxm_8eu22csx_nxlqew1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rfroxm_8eu22csx_nxlqew1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SB_Intrexon_collab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SB_Intrexon_collab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SB_Intrexon_collab1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SB_Intrexon_collab1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sliderPic_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sliderPic_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sliderPic_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sliderPic_51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sliderPic_52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sliderPic_52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Student_Research_LSU4489_Chemistry_Laser_Lab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Student-Research-LSU4489-Chemistry-Laser-Lab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Student_Research_LSU4489_Chemistry_Laser_Lab1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Student-Research-LSU4489-Chemistry-Laser-Lab1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Student_Research_LSU4489_Chemistry_Laser_Lab2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Student-Research-LSU4489-Chemistry-Laser-Lab2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wallpapers_windows_vista_blue_backgrounds_desktop_screen_background_microsoft_operating_computer_systems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wallpapers-windows-vista-blue-backgrounds-desktop-screen-background-microsoft-ope"& _ 
                        "rating-computer-systems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wallpapers_windows_vista_blue_backgrounds_desktop_screen_background_microsoft_operating_computer_systems1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wallpapers-windows-vista-blue-backgrounds-desktop-screen-background-microsoft-ope"& _ 
                        "rating-computer-systems1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
